apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: agents
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-token
  namespace: agents
  annotations:
    kubernetes.io/service-account.name: jenkins
type: kubernetes.io/service-account-token

