apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-ebs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # You may choose a different policy like Delete or Recycle as needed
  awsElasticBlockStore:
    volumeID: vol-0714250639e8feacc  # Ensure this is the correct volume ID
    fsType: ext4
