apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  namespace: agents
spec:
  type: NodePort
  selector:
    app: weather-app 
  ports:
  - port: 80
    targetPort: 5000  
    nodePort: 32000
